sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      python:

install: "pip install flake8==2.5"

script:
  - flake8 *.py
  - python ./test_daemon.py

notifications:
  slack:
    secure: "V9Q1oHrnGwDnQvse0GEmwz4mvihwQYhTLjF2acOqmeC1POkZo18mxqkyjwWFHNr6GxGdUHjjS319tVB6S/MxMJNVo/0cmmSLKkITWBp7alJ6tGTHi4H0UpwWlYGNHVhzlgP4IB1QV2P7AWxr6VlxNHM6GOQJ7oZx3WdsYZfu02c="
